#+TITLE: Omni-Quotes

[[https://travis-ci.org/AdrieanKhisbe/omni-quotes.el][file:https://travis-ci.org/AdrieanKhisbe/omni-quotes.el.svg]]
[[https://coveralls.io/r/AdrieanKhisbe/omni-quotes.el][file:https://coveralls.io/repos/AdrieanKhisbe/omni-quotes.el/badge.svg]]
[[http://melpa.org/#/omni-quotes][file:http://melpa.org/packages/omni-quotes-badge.svg]]
[[http://stable.melpa.org/#/omni-quotes][file:http://stable.melpa.org/packages/omni-quotes-badge.svg]]
[[https://github.com/AdrieanKhisbe/omni-quotes.el/tags][file:https://img.shields.io/github/tag/AdrieanKhisbe/omni-quotes.el.svg]]
[[http://www.gnu.org/licenses/gpl-3.0.html][http://img.shields.io/:license-gpl3-blue.svg]]

/Display all the Quotes!/

* Description

Omni Quotes is there to display quotes on you /Echo Area/ when you are idle.
Whether it's funny stuff, inspirational quotes, or something you try to remember.

* Usage

Just turn on =omni-quotes-mode=, and quotes will appear when you are idle enough.

You can load a quote file with the command =omni-quotes-load-simple-quote-file= and
reload default quotes with =omni-quotes-load-defaults=.
A quote file is just a basic text file with one quote per line.

When you have multiple quote-set it's possible to cycle through them with the commands
=omni-quotes-next-set= and =omni-quotes-prev-set=.


* Installation
You can install it from melpa, with =(package-install 'omni-quotes)=

If you use [[https://github.com/jwiegley/use-package][use-package]] you could use the following config
#+begin_src emacs-lisp
  (use-package omni-quotes
    :bind (("M-s q m" . omni-quotes-mode)
           ("M-s q p" . omni-quotes-prev-set)
           ("M-s q n" . omni-quotes-next-set)
           ("M-s q s" . omni-quotes-shuffle-current-set)
           ("M-s q q" . omni-quotes-display-random-quote))
    :config (omni-quotes-load-simple-quote-file "~/.my-quote" "personal"))
#+end_src

* Configuration
A set of custom is present to customize behavior and appearance of omniquotes.
You can access it through =customize-group 'omni-quotes= where you'll see the list of the customs.

Here are the main ones:

- =omni-quotes-default-quotes= :: List of default quotes
- =omni-quotes-prompt= :: Leading prompt of quotes messages
- =omni-quotes-idle-interval= :: Idle time after which omni-quote start to display quotes
- =omni-quotes-max-repeat= :: Number of omni-quotes will repeat without any activity. If zero there wont be any limit
- =omni-quotes-fading= :: Does the quote fade after some time
- =omni-quotes-fading-delay= :: Delay before the fading effect
- =omni-quotes-fading-duration= :: Time it takes for the quote to fade away
- =omni-quotes-repeat-interval= :: Time interval between two quotes
- =omni-quotes-boring-message-patterns= :: List of message that ca be overwritten by an omni-quote
- =omni-quotes-lighter= :: OmniQuote lighter (name in modeline).

If you want to customize them programaticaly in your config you must use the =customize-set-variable= construct, eg: =(customize-set-variable 'omni-quotes-fading t)=

* Notes

This is an inbuilding package, hence that huge number of building comments accross the code.
(usage of =omni-tags= is recommended :D).

*If you have any remark, refactor suggestion or else, just pose an issue ;)*
