#+TITLE: Omni-Quotes

[[https://travis-ci.org/AdrieanKhisbe/omni-quotes.el][file:https://travis-ci.org/AdrieanKhisbe/omni-quotes.el.svg]]
[[https://coveralls.io/r/AdrieanKhisbe/omni-quotes.el][file:https://coveralls.io/repos/AdrieanKhisbe/omni-quotes.el/badge.svg]]
[[http://melpa.org/#/omni-quotes][file:http://melpa.org/packages/omni-quotes-badge.svg]]
[[http://stable.melpa.org/#/omni-quotes][file:http://stable.melpa.org/packages/omni-quotes-badge.svg]]
[[https://github.com/AdrieanKhisbe/omni-quotes.el/tags][file:https://img.shields.io/github/tag/AdrieanKhisbe/omni-quotes.el.svg]]
[[http://www.gnu.org/licenses/gpl-3.0.html][http://img.shields.io/:license-gpl3-blue.svg]]

/Display all the Quotes!/

* Description

Omni Quotes is there to display quotes on you /Echo Area/ when you are idle.
Whether it's funny stuff, inspirational quotes, or something you try to remember.

* Usage

Just turn on =omni-quotes-mode=, and quotes will appear when you are idle enough.

You can load a quote file with the command =omni-quotes-load-simple-quote-file= and
reload default quotes with =omni-quotes-load-defaults=.
A quote file is just a basic text file with one quote per line.

* Configuration
A set of custom is present to customize behavior and appearance of omniquotes.
You can access it through =customize-group 'omni-quotes= where you'll see the list of the customs.

Here are the main ones:

- =omni-quotes-default-quotes= :: List of default quotes
- =omni-quotes-boring-message-patterns= :: List of message that ca be overwritten by an omni-quote
- =omni-quotes-idle-interval= :: Idle time afterwhich omni-quote start to display quotes
- =omni-quotes-repeat-interval= :: Time interval between two quotes
- =omni-quotes-prompt= :: Leading prompt of quotes messages
- =omni-quotes-lighter= :: OmniQuote lighter (name in modeline).


* Installation
You can install it from melpa, with =(package-install 'omni-quotes)=


* Notes

This is an inbuilding package, hence that huge number of building comments accross the code.
(usage of =omni-tags= is recommended :D).

*If you have any remark, refactor suggestion or else, just pose an issue ;)*
